### ISSUE TITLE
a ^editwarn command 

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#102]
eh probably most of the staff will do ^warn @(player) Spam
ThEy fOrGoT ^RuLeS1?11?
but with this ^editwarn uuuu staff can edit ur fukin warn
like this: ^editwarn (number) Spam, ^rules for rules.
ok thanks bye

**Comment by JRoy** [comment]
^rules is shown by default to the user, but yes an edit warn command is useful.

**Comment by JRoy** [comment]
Added :3
