### ISSUE TITLE
A fishing command that can give you fish that you can sell for random monies

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#125]
ok so heres the fish list:
Common Fish: 1-5
Uncommon Fish: 5-10
Rare Fish: 10-20
Unrare Fish: 20-40
Legendary Fish: 40-100
Unlegendary Fish: 100-150
Legend's Fish: 500-1000
Happyheart's Fish: -1
Fishing Cost: 10
Bait Cost/List (Can buy from the shop; Also can catch while fishing):
Bad Bait: 5
Good Bait: 50
Rare Bait: 100
Legendary Bait: 500

**Comment by JRoy** [comment]
Awesome Idea! Will add.

**Comment by gcm-0** [comment]
Instead of fish and bait you could make it something league or happyheart related.

**Comment by gcm-0** [comment]
also the prices aren't balanced since a common fish has a large chance of giving you a loss, you would need to compensate for that.

**Comment by Alyasx** [comment]
there should be a cooldown like 20-30 seconds

**Comment by gcm-0** [comment]
yeah probably, it could be random ranging from 10 seconds to 10 minutes with messages like "random hurricane" to "I needed to put the fish in a bucket"

**Comment by Alyasx** [comment]
Also maybe a 50/50 Fail messages?..
example: "My bait fell into the water, FRICK." or, "A tree fell on you, But you manage to survive the incident."

**Comment by gcm-0** [comment]
greater chance to get the fish than 50/50 but yeah.

**Comment by JRoy** [comment]
Too lazy to add this

**Comment by JRoy** [comment]
@bumbleblake may want this

**Comment by JRoy** [comment]
Closing (In-Active)
