### ISSUE TITLE
Automatic EXP-Spammer remover

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#127]
title is the thing so bye

**Comment by NotLe0n** [comment]
yes

**Comment by ghost** [comment]
hello this message is in #bot-meta horray :)
hi guys

**Comment by Alyasx** [comment]
it'ill probably go like this
^expspammer (time) (player)
examlpe: ^expspammer 9999y @Teddy1424#4706
Exp spam'd @Teddy1424 for 9999y!

**Comment by JRoy** [comment]
Should be fixed in commit 0f8f617
