### ISSUE TITLE
[BUG] broke image icon in embed

### ISSUE THREAD

**Issue by NotLe0n** [JRoy/happybot#129]
There is some kind of broken image icon at the bottom of the starred messages embeds. pls fix
![image](https://user-images.githubusercontent.com/26361108/36067619-c82f8448-0ec0-11e8-9fbd-5600c7de3ae4.png)

**Comment by Alyasx** [comment]
Yes, Yes that happens to me.
![image](https://user-images.githubusercontent.com/24978498/36074353-16604582-0f50-11e8-8dd0-1e819d527143.png)
