### ISSUE TITLE
^vwarn (Verbal warning command)

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#130]
Verbal warning and what it should do:
Obviously, verbal warns.
2 verbal warnings = 1 warn (The staff member can change it)
2 Verbal warnings = warn (should be automatic)
It's just for new people or those who haven't read the rules.
Or StAFf mEMBERS thAT aRE not sTrICT (BrUMBLE GumPle)

**Comment by JRoy** [comment]
No longer makes sense
