### ISSUE TITLE
Happybot ^theme avatar change

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#139]
![aa](https://user-images.githubusercontent.com/24978498/38202820-c8e205f2-36a5-11e8-80b8-4402d490f502.png)
valentine maeyb??!?!?

**Comment by JRoy** [comment]
@Alyasx this has been made in my other thingy, discord-themer. This will get addressed in #144

**Comment by Alyasx** [comment]
yeah i meant the bot's pfp
