### ISSUE TITLE
^mention (twitter,git,updates)

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#142]
hi how about you make the ^mention command give multiple roles at once, example xd:
^mention git, twitter, updates (all at once)
You will now receive notifications from git, twitter, updates
doing this means no chat flood xd
chat fklood:
^mention git
You will now receive notifications from git!
^mention twitter
You will now receive notifications from twitter!
^mention updates
You will now receive notifications from updates!

**Comment by JRoy** [comment]
Note to self: String#contains with a shit ton of if statements
