### ISSUE TITLE
^whois command

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#151]
yes you all agree also dont forget about the past names, nicknames, account registered, etc.
thANKS aND byE FucK  You KeKmiT!

**Comment by Alyasx** [comment]
teddy no u

**Comment by JRoy** [comment]
Log Username change event

SQL Data:
id, discordid, new name

**Comment by JRoy** [comment]
This is stupid no

**Comment by Alyasx** [comment]
i thought you said ur gonna make this what a scam.
hi b ass ic here
h
