### ISSUE TITLE
Fix YouTube checker

### ISSUE THREAD

**Issue by JRoy** [JRoy/happybot#173]
Idfk

**Comment by JRoy** [comment]
it was "discord's fault"

**Comment by gcm-0** [comment]
Mmmmhmmm definitely

**Comment by gcm-0** [comment]
It’s not like it just did the same on starred messages

**Comment by JRoy** [comment]
@AllStarDiscord It actually was, discord's api was misfiring and my bot kept trying to send more requests thinking they failed, but they didn't :LUL:
