### ISSUE TITLE
^borrow command 

### ISSUE THREAD

**Issue by NotLe0n** [JRoy/happybot#179]
A command to borrow coins from someone.

user1: `^borrow <user2> <amount>`
Bot: `@<user1> wants to borrow <amount> coins, @<user2>`
           `type ^borrow accept @<user1> to accept his request`

If user2 accepts, user1 will get the amount of coins and will have to repay them until everything is repayed.

this is how I imagine it to work.

**Comment by JRoy** [comment]
Just use ^money pay
