### ISSUE TITLE
true or false editing a message = delet

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#181]
editing your message should make ur message get deleted
yes because anyone can do this
the person below is cool
the person below is gay (edited)

**Comment by JRoy** [comment]
I guess I could do that, currently the bot just makes sure that the message is valid once editied but I could delete it.

**Comment by Alyasx** [comment]
it just randomly sends you a message telling you that you replied to your own true/false message 🤔 that's gay, and it just sometimes deletes your messages probably telling you replied to yourself (you didnt reply to yourself)

**Comment by JRoy** [comment]
I removed the reply to your own thing but I can make the format more easy to understand

**Comment by JRoy** [comment]
Closed as of commit 7e24670
