### ISSUE TITLE
true or false warn system xd

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#182]
if you delete your message in true or false it should send you like a warn thing where if you delete your message like 5 times you automatically get warned because some gays delete their message

**Comment by JRoy** [comment]
Discord doesn't let anyone see *who* deleted a message so this cannot be implemented

**Comment by okx-code** [comment]
Actually, it can if you look at the audit log.

**Comment by JRoy** [comment]
@okx-code: Audit-Log does not trace user deletions

**Comment by okx-code** [comment]
If you don't see a deletion in the audit log you can assume the deletion was by the user.

**Comment by JRoy** [comment]
Does Discord have endpoints for the audit log also imo I don't see this as that big of an issue
