### ISSUE TITLE
Happybot doesn't dm you when using ^help

### ISSUE THREAD

**Issue by NotLe0n** [JRoy/happybot#190]
you don't get a dm when you do ^help

**Comment by JRoy** [comment]
this is an isolated issue with your privacy settings, not happybot

**Comment by okx-code** [comment]
happybot could send a message saying DMs are closed. This would be more helpful.

**Comment by JRoy** [comment]
@okx-code: I do this
https://github.com/JRoy/happybot/blob/7b56c1c24a31dda25e5caa5ce3e5be6e1682dd51/src/main/java/io/github/jroy/happybot/commands/HelpCommand.java#L47-L48
