### ISSUE TITLE
Say how long to wait untill you can rob one again

### ISSUE THREAD

**Issue by NotLe0n** [JRoy/happybot#191]
If you try to rob someone twice in the same day, it should say how long you have to wait.

e.g:
Happy Bot **[BOT]**
You may only rob a user once a day! You can rob them again in 2 hours.

**Comment by TheLonelySheep** [comment]
give git contributor role pls

**Comment by okx-code** [comment]
maybe when you write some actual code

**Comment by TheLonelySheep** [comment]
what? write code? I was told I need to make lots of issues and "help" (#82) 
I certainly helped by reporting bugs and making suggestions.
