### ISSUE TITLE
Can we kill happybot every hour or something

### ISSUE THREAD

**Issue by JRoy** [JRoy/happybot#196]
the jvm lets to collect garbage, meaning our timers get collected. (why don't the jvm garbage collect the entire bot because bot is garbage??!)

Um so:
* Fire a webhook(?) in #general every x hours with the eric andre "we'll be right back" thing.
* Kill Java Process
* The bot restarts with its timers in tack.
* Profit?

**Comment by okx-code** [comment]
This is honestly just a workaround for bad code. You need to just make sure the timers are referenced to and don't get garbage collected.

**Comment by JRoy** [comment]
@okx-code I know, this was supposed to be a joke

**Comment by okx-code** [comment]
a bad one at that
