### ISSUE TITLE
Create a coin gambling system with SQL 

### ISSUE THREAD

**Issue by JRoy** [JRoy/happybot#46]
This would add some reward and fun for chatting in the guild. Coins could allow for rewards

**Comment by SinisterZek** [comment]
How would this work?

**Comment by bumbleblake** [comment]
@SinisterZek SQL is an online database system. You could earn "coins" and maybe Josh may implement gambling games to earn or lose them on. Each user's balance gets stored online, so even if the bot gets reset, you don't lose any money.
