### ISSUE TITLE
Read vv

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#57]
Theres this mention/ping issue with #bot-git and #updates and #twitter, and i have a great idea maybe it will work..
So here goes nothing.. So it should work like this: When the github bot says something spongebot (or some other bot) should mention/ping the people that want to get mentioned/pinged same thing with #updates and #twitter.

**Comment by WheezyGold7931** [comment]
Addressed in #9

**Comment by JRoy** [comment]
Addressed in #81
