### ISSUE TITLE
Make a ^money mine (or just ^mine)

### ISSUE THREAD

**Issue by Alyasx** [JRoy/happybot#77]
mining can get you money
you can only use the mining command once a 1 hour
i donut have a brain

**Comment by Alyasx** [comment]
uhhh the pickaxe should cost like 80 monies or so.
^money shop too (i know thats coming after like 5 days or so idfk)
^money buy ⛏ 
(copy of another bot loloololol)

**Comment by JRoy** [comment]
What would mining do tho

**Comment by JRoy** [comment]
And how would a pickaxe help that
