### ISSUE TITLE
Warning System

### ISSUE THREAD

**Issue by JRoy** [JRoy/happybot#94]
Convert over to our own custom warning system. We would create a WarningManager class that would manage warnings and the SQL connection. We would have to take in SQLManager in our constructor so we could grab the connection that way. 

^warn <user> <reason>
^delwarn <id>
^warnings <user>

All helper commands

For warnings use a string builder and a result set

Also on ^warn make an embed in #log

**Comment by Techno-coder** [comment]
Be sure to use PreparedStatements to avoid SQL Injection issues

**Comment by JRoy** [comment]
@Techno-coder Absolutely, as we are not validating input and it is raw text, that would be a must.
